### ISSUE TITLE
PT sound Pack

### ISSUE THREAD

**Issue by jreis1** [Hobby4life/ETHOS-OpenTX-Soundpacks-EN-NL#1]
Hey there, 

I've been doing the sound translation to Portuguese for Ethos based on your files and using TTS automate. 
It seems that Ethos uses other Text-to-Speech tool rather than TTS. 

2 questions: 
- The "official" Ethos Audio file only has 198 inputs. Yours have 420. Why is that ? (i'm tring not miss anything here)

- As I've already done all translations based on your files, are you willing to accommodate PT sound pack in your directory?  if so, please find attached the .psv file below.  It is already phonetically prepared for "Amazon Polly" "Inês, Portuguese, Female"
[ETHOS PT + H4L(Ethos1.09).zip](https://github.com/Hobby4life/ETHOS-OpenTX-Soundpacks-EN-NL/files/6701360/ETHOS.PT.%2B.H4L.Ethos1.09.zip)

**Comment by Hobby4life** [comment]
There are 2 files.. Ethos.psv and Ethos-H4L.psv

the  Ehtos.psv is the default pack.

**Comment by jreis1** [comment]
> There are 2 files.. Ethos EN.psv and Ethos EN - H4L.psv
> 
> the Ehtos EN.psv is the default pack.
> Ethos EN- H4L.psv is default + my own created sounds over the years.

Perfect :)
Just one more question, do you know if the phonetics used in TTS are also compatible the audio generated by FRsky ? 
Ex: "RSSI "in PT must be interpreted as "ÉrreÉssÉssÌ" to sound right in TTS.

**Comment by Hobby4life** [comment]
You have to tweak the text so the phonetics will sound right..
I have to do that in dutch too :-), some words look really weird but pronounced perfectly.
